#!/usr/bin/env bash
# Idempotent Cloud Agent install for Pod Automator.
# Installs system services (PostgreSQL + Redis) and Node dependencies, then
# ensures the local database and a key-free development .env exist.
# Safe to re-run: every step checks for existing state before acting.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PG_VERSION=16
PG_CLUSTER=main

echo "==> Installing system packages (PostgreSQL, Redis) if missing"
if ! command -v pg_ctlcluster >/dev/null 2>&1 || ! command -v redis-server >/dev/null 2>&1; then
  sudo apt-get update -y
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql postgresql-contrib redis-server
else
  echo "    PostgreSQL and Redis already installed."
fi

echo "==> Installing Node dependencies"
npm ci

echo "==> Ensuring PostgreSQL cluster is running"
if ! pg_lsclusters -h 2>/dev/null | awk '{print $4}' | grep -q online; then
  sudo pg_ctlcluster "$PG_VERSION" "$PG_CLUSTER" start || true
fi

echo "==> Ensuring 'pod' role and 'pod_automator' database exist"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<'SQL'
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'pod') THEN
    CREATE ROLE pod LOGIN PASSWORD 'pod';
  END IF;
END$$;
SQL
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='pod_automator'" | grep -q 1; then
  sudo -u postgres createdb -O pod pod_automator
fi
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE pod_automator TO pod;" >/dev/null

echo "==> Ensuring development .env exists (key-free, mock AI provider)"
if [ ! -f "$REPO_ROOT/.env" ]; then
  AUTH_SECRET="$(node -e "console.log(require('crypto').randomBytes(24).toString('hex'))")"
  cat > "$REPO_ROOT/.env" <<ENV
# Auto-generated by .cursor/install.sh — local, key-free development config.
NODE_ENV=development
HOST=localhost
PORT=3000
API_PUBLIC_PORT=3000
PUBLIC_HOST=localhost
WEB_BIND_HOST=localhost
PUBLIC_WEB_HOST=localhost
WEB_HOST=localhost
WEB_PORT=5173
DATABASE_URL=postgres://pod:pod@localhost:5432/pod_automator
REDIS_URL=redis://localhost:6379
AUTH_SECRET=${AUTH_SECRET}
AUTH_MODE=development
AI_PROVIDER=mock
OPENROUTER_IMAGE_MODEL=google/gemini-3.1-flash-image
FAL_IMAGE_MODEL=fal-ai/flux/schnell
GEMINI_MOCKUP_MODEL=gemini-3-pro-image
MOCKUP_AI_PROVIDER=gemini
HUGGINGFACE_IMAGE_MODEL=black-forest-labs/FLUX.2-klein-9B
OLLAMA_IMAGE_MODEL=x/flux2-klein
OLLAMA_IMAGE_MODEL_9B=x/flux2-klein:9b
OLLAMA_IMAGE_MODEL_PREFIX=x/
TRANSFORM_DRIVER=sharp
TRANSFORM_MODEL_CACHE_DIR=./data/model-cache
TRANSFORM_MAX_DIMENSIONS=2400
STORAGE_DRIVER=local
STORAGE_DIR=./data/uploads
S3_ENDPOINT=http://localhost:9000
S3_REGION=us-east-1
S3_BUCKET=pod-assets
S3_ACCESS_KEY=minioadmin
S3_SECRET_KEY=minioadmin
ENV
  echo "    Wrote $REPO_ROOT/.env"
else
  echo "    .env already present — leaving it untouched."
fi

echo "==> Bootstrapping database schema"
npm run db:bootstrap

echo "==> Install complete."
