import { jsonb, integer, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from 'drizzle-orm/pg-core'

const timestamps = { createdAt: timestamp('created_at').defaultNow().notNull(), updatedAt: timestamp('updated_at').defaultNow().notNull() }

export const users = pgTable('users', { id: uuid('id').defaultRandom().primaryKey(), email: varchar('email', { length: 255 }).notNull().unique(), name: varchar('name', { length: 120 }).notNull(), googleId: varchar('google_id', { length: 255 }), ...timestamps })
export const workspaces = pgTable('workspaces', { id: uuid('id').defaultRandom().primaryKey(), ownerId: uuid('owner_id').notNull().references(() => users.id), name: varchar('name', { length: 120 }).notNull(), ...timestamps })
export const workflows = pgTable('workflows', { id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id), name: varchar('name', { length: 160 }).notNull(), version: integer('version').default(1).notNull(), definitionGraph: jsonb('definition_graph').notNull(), ...timestamps })
export const runs = pgTable('runs', { id: uuid('id').defaultRandom().primaryKey(), workflowId: uuid('workflow_id').notNull().references(() => workflows.id), status: varchar('status', { length: 30 }).notNull().default('pending'), progressPercent: integer('progress_percent').notNull().default(0), config: jsonb('config').notNull(), errorLog: text('error_log'), ...timestamps })
export const assets = pgTable('assets', { id: uuid('id').defaultRandom().primaryKey(), runId: uuid('run_id').references(() => runs.id), workspaceId: uuid('workspace_id').references(() => workspaces.id), type: varchar('type', { length: 30 }).notNull(), name: varchar('name', { length: 255 }).notNull(), storagePath: text('storage_path').notNull(), contentType: varchar('content_type', { length: 120 }).notNull(), metadata: jsonb('metadata').notNull().default({}), ...timestamps })
export const productVariants = pgTable('product_variants', { id: uuid('id').defaultRandom().primaryKey(), runId: uuid('run_id').notNull().references(() => runs.id), designAssetId: uuid('design_asset_id').notNull().references(() => assets.id), productType: varchar('product_type', { length: 40 }).notNull(), status: varchar('status', { length: 30 }).notNull().default('pending'), ...timestamps })
export const mockupTemplates = pgTable('mockup_templates', { id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id), name: varchar('name', { length: 160 }).notNull(), type: varchar('type', { length: 30 }).notNull(), productType: varchar('product_type', { length: 40 }).notNull(), config: jsonb('config').notNull(), ...timestamps })
export const promptTemplates = pgTable('prompt_templates', { id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id), name: varchar('name', { length: 160 }).notNull(), prompt: text('prompt').notNull(), provider: varchar('provider', { length: 40 }).notNull().default('fal'), model: varchar('model', { length: 160 }), description: varchar('description', { length: 255 }), ...timestamps })
export const workspaceConnections = pgTable('workspace_connections', { id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id), provider: varchar('provider', { length: 40 }).notNull(), defaultModel: varchar('default_model', { length: 160 }).notNull(), enabled: varchar('enabled', { length: 10 }).notNull().default('true'), ...timestamps })
export const mockups = pgTable('mockups', { id: uuid('id').defaultRandom().primaryKey(), productVariantId: uuid('product_variant_id').notNull().references(() => productVariants.id), templateId: uuid('template_id').references(() => mockupTemplates.id), storagePath: text('storage_path'), status: varchar('status', { length: 30 }).notNull().default('pending'), ...timestamps })
export const marketplaceConnections = pgTable('marketplace_connections', { id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id), provider: varchar('provider', { length: 40 }).notNull(), accessTokenEncrypted: text('access_token_encrypted'), refreshTokenEncrypted: text('refresh_token_encrypted'), tokenExpiresAt: timestamp('token_expires_at'), scopes: text('scopes').array().notNull().default([]), externalAccountId: varchar('external_account_id', { length: 255 }), externalAccountName: varchar('external_account_name', { length: 255 }), state: varchar('state', { length: 30 }).notNull().default('disconnected'), settings: jsonb('settings').notNull().default({}), lastError: text('last_error'), ...timestamps }, (table) => ({ workspaceProvider: uniqueIndex('marketplace_connections_workspace_provider').on(table.workspaceId, table.provider) }))
export const marketplaceOauthSessions = pgTable('marketplace_oauth_sessions', { id: uuid('id').defaultRandom().primaryKey(), workspaceId: uuid('workspace_id').notNull().references(() => workspaces.id), provider: varchar('provider', { length: 40 }).notNull(), stateHash: varchar('state_hash', { length: 64 }).notNull().unique(), verifierEncrypted: text('verifier_encrypted').notNull(), expiresAt: timestamp('expires_at').notNull(), consumedAt: timestamp('consumed_at'), ...timestamps })
export const marketplaceListings = pgTable('marketplace_listings', { id: uuid('id').defaultRandom().primaryKey(), productVariantId: uuid('product_variant_id').notNull().references(() => productVariants.id), marketplace: varchar('marketplace', { length: 40 }).notNull(), externalId: varchar('external_id', { length: 255 }), externalUrl: text('external_url'), status: varchar('status', { length: 30 }).notNull().default('preview'), metadata: jsonb('metadata').notNull().default({}), lastError: text('last_error'), failedStage: varchar('failed_stage', { length: 30 }), syncedAt: timestamp('synced_at'), publishedAt: timestamp('published_at'), ...timestamps }, (table) => ({ variantMarketplace: uniqueIndex('marketplace_listings_variant_marketplace').on(table.productVariantId, table.marketplace) }))
export const jobs = pgTable('jobs', { id: uuid('id').defaultRandom().primaryKey(), runId: uuid('run_id').notNull().references(() => runs.id), stepName: varchar('step_name', { length: 80 }).notNull(), status: varchar('status', { length: 30 }).notNull().default('queued'), retryCount: integer('retry_count').notNull().default(0), errorLog: text('error_log'), ...timestamps })
